[package]
name = "argon2"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blake2-rfc = "0.2.16"
base64 = "0.13.0"

[dev-dependencies]
hex-literal = "0.3.3"